export { BaseEntity } from './base.js';
export { EntityRegistry } from './registry.js';

// Explicitly export new entities to ensure visibility and registration
export { PoliceCarEntity } from './policeCar.js';
export { DeliveryVanEntity } from './deliveryVan.js';
export { SkyGardenTowerEntity } from './skyGardenTower.js';
export { RadioTowerEntity } from './radioTower.js';
export { NeonSignEntity } from './neonSign.js';
export { HVACEntity } from './hvac.js';
export { LandingPadEntity } from './landingPad.js';
export { RadarDishEntity } from './radarDish.js';
export { WoodenFenceEntity, PicketFenceEntity, ChainLinkFenceEntity, CementWallEntity } from './fence.js';
export { LilyPondEntity } from './lilyPond.js';
export { BurgerJointEntity, OfficeParkEntity, ModernTowerEntity } from './commercial.js';
export { HouseModernEntity, HouseCottageEntity, HousePorchEntity, ApartmentBlockEntity } from './residential.js';
export { SidewalkEntity, SidewalkCornerEntity } from './infrastructure.js';
export { HouseGardenEntity } from './houseGarden.js';
export { HouseVerandaEntity } from './houseVeranda.js';
export { IntersectionEntity } from './intersections.js';
export { BusStopEntity } from './busStop.js';
export { PlayerStartEntity } from './playerStart.js';
export { WaterFountainEntity } from './waterFountain.js';
export { ObservatoryEntity } from './observatory.js';
export { FireHydrantEntity } from './fireHydrant.js';
export { FireStationEntity } from './fireStation.js';
export { WindSockEntity } from './windsock.js';
export { ChargingStationEntity } from './chargingStation.js';
export { LotusPondEntity } from './lotusPond.js';
export { MushroomPatchEntity } from './mushroomPatch.js';
export { RunwayEdgeLightEntity } from './runwayEdgeLight.js';
export { JetBridgeEntity } from './jetBridge.js';
export { ConstructionBarrierEntity } from './constructionBarrier.js';
export { SolarPanelEntity } from './solarPanel.js';
export { MarketStallEntity } from './marketStall.js';
export { PinkVendingMachineEntity } from './pinkVendingMachine.js';
export { VendingMachineEntity } from './vendingMachine.js';
export { FuturisticVendingMachineEntity } from './futuristicVendingMachine.js';
export { WindTurbineEntity } from './windTurbine.js';
export { ScooterDockEntity } from './scooterDock.js';
export { BoostGateEntity } from './boostGate.js';
export { FuturisticMailboxEntity } from './futuristicMailbox.js';
export { AerialBeaconEntity } from './aerialBeacon.js';
export { FluxEmitterEntity } from './fluxEmitter.js';
export { RiverBuoyEntity } from './riverBuoy.js';
export { PowerTransformerAlternateEntity } from './powerTransformerAlternate.js';
export { FuturisticEmergencySirenEntity } from './futuristicEmergencySiren.js';
export { GazeboEntity } from './gazebo.js';
export { CementMixerEntity } from './cementMixer.js';
export { FoodTruckEntity } from './foodTruck.js';
export { LighthouseEntity } from './lighthouse.js';
export { ShippingContainerEntity } from './shippingContainer.js';
export { DumpsterEntity } from './dumpster.js';
export { PortaPottyEntity } from './portaPotty.js';
export { PhoneBoothEntity } from './phoneBooth.js';
export { TugboatEntity } from './tugboat.js';
export { HologramKioskEntity } from './hologramKiosk.js';
export { SpectralBeaconEntity } from './spectralBeacon.js';
export { GardenLanternEntity } from './gardenLantern.js';
export { SunflowerPatchEntity } from './sunflowerPatch.js';
export { PlanterBoxEntity } from './planterBox.js';
export { PorchLightEntity } from './porchLight.js';
export { PorchSwingEntity } from './porchSwing.js';
export { HedgeEntity } from './hedge.js';
export { LaundryDryingRackEntity } from './laundryDryingRack.js';
export { BirchTreeEntity } from './birchTree.js';
export { FlowerArchEntity } from './flowerArch.js';
export { CourierDroneEntity } from './courierDrone.js';
export { PulseReactorEntity } from './pulseReactor.js';
export { GardenPlanterEntity } from './gardenPlanter.js';
export { RooftopChimneyEntity } from './rooftopChimney.js';
export { WindowACUnitEntity } from './windowACUnit.js';
export { RooftopWaterTowerEntity } from './rooftopWaterTower.js';
export { MapleTreeEntity } from './mapleTree.js';
export { CargoDroneEntity } from './cargoDrone.js';
export { BikeRackEntity } from './bikeRack.js';
export { SmartBenchEntity } from './smartBench.js';
export { KioskEntity } from './kiosk.js';
export { MallDirectoryEntity } from './mallDirectory.js';
export { BalconyLaundryLineEntity } from './balconyLaundryLine.js';
export { ApartmentLaundryLineEntity } from './apartmentLaundryLine.js';
export { ATMEntity } from './atm.js';
export { DJEntity } from './DJ.js';
export { BuskerEntity } from './busker.js';
export { JugglerEntity } from './juggler.js';
export { DroneMechanicEntity } from './droneMechanic.js';
export { AlleyCatStatueEntity } from './alleyCatStatue.js';
export { CityBlockEntity } from './cityBlock.js';
export { RaccoonTrashCanEntity } from './raccoonTrashCan.js';
export { OilPumpJackEntity } from './oilPumpJack.js';
export { ParcelLockerEntity } from './parcelLocker.js';
export { LaundryBalconyEntity } from './laundryBalcony.js';
export { BiolumeTreeEntity } from './biolumeTree.js';
export { CypressTreeEntity } from './cypressTree.js';
export { SentryPylonEntity } from './sentryPylon.js';
export { SentryTurretEntity } from './sentryTurret.js';
export { SubwayVentEntity } from './subwayVent.js';


// Eagerly load all entity modules to trigger their registrations.
// Vite will execute each module once, ensuring EntityRegistry is populated
// without manual imports.
import.meta.glob('./*.js', { eager: true });
